name: caller

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  variables:
    name: Compute outputs call
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ENVSECRET: ${{ secrets.ENVSECRET }}
    outputs:
      secret_out: ${{ secrets.ENVSECRET }}   
    steps:
      - name: Outputs secret value
        id: secret_val
        run: |
          echo $ENVSECRET | sed 's/./& /g'

  call_runner:
    name: call runner
    uses: ./.github/workflows/runner.yml
    with:
      environment: test
      secret_val: ${{ needs.variables.outputs.secret_out }}
    secrets: inherit
