name: ci

on:
  workflow_dispatch:

jobs:
  dev:
    name: dev
    uses: ./.github/workflows/caller.yml
    with:
      environment: dev
    secrets: inherit

  test:
    name: test
    uses: ./.github/workflows/caller.yml
    with:
      environment: test
    secrets: inherit
    
  stage:
    name: stage
    uses: ./.github/workflows/caller.yml
    with:
      environment: stage
    secrets: inherit
    
  prod:
    name: prod1
    uses: ./.github/workflows/caller.yml
    with:
      environment: prod
    secrets: inherit    

  prod2:
    name: prod2
    uses: ./.github/workflows/caller.yml
    with:
      environment: prod
    secrets: inherit    
  
  prod3:
    name: prod3
    uses: ./.github/workflows/caller.yml
    with:
      environment: prod
    secrets: inherit          