name: ci_self

on:
  workflow_dispatch:

jobs:

  test_secrets:
    name: Test Secrets
    runs-on: ubuntu-latest
    steps:
      - name: getsecret
        run: |
          my_secret=gh secret get ENVSECRET --env dev
      
        dev:
    name: dev
    uses: ./.github/workflows/self.yml
    with:
      environment: dev
      self: ${{ gh secret get ENVSECRET --env dev }}
    secrets: inherit