name: ci_self

on:
  workflow_dispatch:

jobs:
  dev:
    name: dev
    uses: ./.github/workflows/self.yml
    with:
      environment: dev
      self: ${{ gh secret get ENVSECRET --env dev }}
    secrets: inherit