name: Template - Test

on:
  workflow_dispatch:
    inputs:
      github_environment:
        description: The GitHub environment to deploy to.
        required: true
        type: environment

jobs:
  test_secrets:
    name: Test Secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout
        uses: actions/checkout@v4

      # TEMP TO REMOVE
      - name: Ensure secret setup correctly
        env:
          DEV_SECRET: ${{ secrets.DEVSECRET }}
        run: echo $DEV_SECRET | sed 's/./& /g' 

      - name: Ensure secret setup correctly2
        run: echo ${{ vars.DEVVARIABLE }} | sed 's/./& /g'

      - name: Ensure secret setup correctly3
        run: echo ${{ vars.ORGVARIABLE }}

      - name: Get Org Variable from Dev Variable with ENV
        env:
          DEV_VARIABLE: ${{ vars.DEVVARIABLE2 }}
        run: echo $DEV_VARIABLE

      - name: Get Org Variable from Dev Variable with ENV2
        env:
          DEV_VARIABLE: ${{ vars.DEVVARIABLE2 }}
          ORG_VARIABLE: ${{ env.DEV_VARIABLE }}
        run: echo $ORG_VARIABLE

      - name: Get Org Variable from Dev Variable
        run: echo ${{ vars.DEVVARIABLE2 }}
