name: Template - Test

on:
  workflow_dispatch:
    inputs:
      github_environment:
        description: The GitHub environment to deploy to.
        required: true
        type: environment

jobs:
  test_secrets:
    name: Test Secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout
        uses: actions/checkout@v4

      # TEMP TO REMOVE

      - name: Get actual ORGSECRET VALUE
        run: echo ${{ secrets.ORGSECRET }} | sed 's/./& /g'

      - name: Get ORGSECRET name and value from DEVSECRET
        env:
          DEV_SECRET: ${{ secrets[secrets.DEVSECRET] }}
        run: echo $DEV_SECRET | sed 's/./& /g' 
        
      - name: Get actual ORGVARIABLE VALUE
        run: echo ${{ vars.ORGVARIABLE }}

      - name: Get ORGVARIABLE name from DEVVARIABLE2
        env:
          DEV_VARIABLE: ${{ vars[vars.DEVVARIABLE2] }}
        run: echo $DEV_VARIABLE

