name: runner

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment'
        required: true
        default: 'dev'
      non_secret_out:
        type: string
        description: 'Non secret value'
        required: true
    secrets:
      ENVSECRET:
        required: false
      

jobs:
  variables:
    name: Compute outputs run
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ENVSECRET: ${{ secrets.ENVSECRET }}
      ENVSECRET_PARAM: ${{ secrets.secret_val }}
      ENVNONSECRET_PARAM: ${{ inputs.non_secret_out }}
    steps:
      - name: Outputs secret value environment
        id: secret_val_env
        run: |
          echo $ENVSECRET | sed 's/./& /g'
      - name: Outputs secret value parameter
        id: secret_val_param
        run: |
          echo $ENVSECRET_PARAM | sed 's/./& /g'
      - name: Outputs non secret value
        id: non_secret_val_param
        run: |
          echo $ENVNONSECRET_PARAM | sed 's/./& /g'