name: runner

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  variables:
    name: Compute outputs run
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ENVSECRET: ${{ secrets.ENVSECRET }}
    steps:
      - name: Outputs secret value
        id: secret_val
        run: |
          echo $ENVSECRET | sed 's/./& /g'