name: runner

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment'
        required: true
        default: 'dev'
      secret_val:
        type: string
        description: 'Secret value'
        required: true

jobs:
  variables:
    name: Compute outputs run
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ENVSECRET: ${{ secrets.ENVSECRET }}
      ENVSECRET_PARAM: ${{ inputs.secret_val }}
    steps:
      - name: Outputs secret value environment
        id: secret_val_env
        run: |
          echo $ENVSECRET | sed 's/./& /g'
      - name: Outputs secret value parameter
        id: secret_val_param
        run: |
          echo $ENVSECRET_PARAM | sed 's/./& /g'