name: self

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment'
        required: true
        default: 'dev'
      self:
        type: string
        description: 'Is self'
        required: true
    secrets: 
      creds:
        required: true


jobs:
  variables:
    name: Compute outputs call
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ENVSECRET: ${{ secrets.ENVSECRET }}
    outputs:
      secret_out: ${{ secrets.ENVSECRET }}   
      non_secret_out: "hello this is me"
      self: ${{ inputs.self }}
    steps:
      - name: Outputs secret value
        id: secret_val
        run: |
          echo $ENVSECRET | sed 's/./& /g'

  run_self:
      name: run self
      runs-on: ubuntu-latest
      needs: variables
      steps:
        - name: Run self
          run: |
            echo "self: ${{ needs.variables.outputs.self }}"




  # call_self:
  #   name: call self
  #   needs: variables
  #   if: ${{ needs.variables.outputs.self == 'first' }}
  #   uses: ./.github/workflows/self.yml
  #   with:
  #     environment: test
  #     self: 'second'
  #   secrets: inherit
